---
- name: Configure and deploy InsureMe app
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: ['docker.io']
        state: present
        update_cache: yes

    - name: Start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Pull Docker Image
      shell: docker pull sarafabhinav1997/insureme-app:latest

    - name: Stop existing container if running
      shell: docker stop insureme || true && docker rm -f insureme || true

    - name: Run container
      shell: docker run -d -p 8084:8081 --name insureme sarafabhinav1997/financeme-app:latest
